import { expect, test } from '@playwright/test'
import { advanceTicks, holdKey, moveAxis, pressKey, readState, rotateCameraCardinal, startChapter, waitForState } from './runtime-helpers'

async function recordPlayerCore(page: Parameters<typeof startChapter>[0]): Promise<void> {
  await rotateCameraCardinal(page)
  await pressKey(page, 'r')
  await holdKey(page, 'd', 54)
  await pressKey(page, 'e')
  await expect.poll(async () => (await readState(page)).cores['memory-core']?.carriedBy).toBe('player')
}

test.describe('Chapter 3 independent negative runtime contracts', () => {
  test('A — direct Player receiver interaction cannot fill without the Core', async ({ page }) => {
    test.setTimeout(150_000)
    await startChapter(page, 3)
    await rotateCameraCardinal(page)
    await moveAxis(page, 'z', 1.6, 'reach receiver lane')
    await holdKey(page, 'd', 90)
    await pressKey(page, 'e')
    const current = await readState(page)
    expect(current.player?.position.x ?? 99, 'the closed divider still blocks the receiver lane').toBeLessThan(3.6)
    expect(current.objectives.facts).not.toContain('receiver-filled')
  })

  test('B — carried Core cannot use the Player one-way route', async ({ page }) => {
    test.setTimeout(150_000)
    await startChapter(page, 3)
    await recordPlayerCore(page)
    await moveAxis(page, 'z', -2, 'approach the Player route while carrying')
    await moveAxis(page, 'x', 0.5, 'push carried Core into the physical gate')
    await advanceTicks(page, 20)
    const current = await readState(page)
    expect(current.cores['memory-core']?.position.x ?? 99).toBeLessThan(0.5)
    expect(current.objectives.facts).not.toContain('temporal-gate-rejected')
  })

  test('C — thrown Core is stopped by the temporal gate collider', async ({ page }) => {
    test.setTimeout(150_000)
    await startChapter(page, 3)
    await recordPlayerCore(page)
    await moveAxis(page, 'z', -2.3, 'enter the Player route')
    await moveAxis(page, 'x', -0.8, 'reach west throw point')
    await holdKey(page, 'd', 1)
    await pressKey(page, 'k')
    await advanceTicks(page, 30)
    const core = (await readState(page)).cores['memory-core']
    expect(core?.carriedBy).toBeUndefined()
    expect(core?.position.x ?? 99).toBeLessThan(3.6)
  })

  test('D — a second thrown attempt cannot bypass the gate', async ({ page }) => {
    test.setTimeout(150_000)
    await startChapter(page, 3)
    await recordPlayerCore(page)
    await moveAxis(page, 'z', -2.3, 'enter the Player route')
    await moveAxis(page, 'x', -0.8, 'reach west throw point')
    await holdKey(page, 'd', 1)
    await pressKey(page, 'k')
    await advanceTicks(page, 20)
    const firstThrow = await readState(page)
    expect(firstThrow.cores['memory-core']?.carriedBy).toBeUndefined()
    expect(firstThrow.cores['memory-core']?.position.x ?? 99).toBeLessThan(4)
    await pressKey(page, 'e')
    const secondAttempt = await readState(page)
    expect(secondAttempt.cores['memory-core']?.carriedBy).toBeUndefined()
    expect(secondAttempt.cores['memory-core']?.position.x ?? 99).toBeLessThan(4)
  })

  test('E — divider edge movement does not bypass the authored crossings', async ({ page }) => {
    test.setTimeout(150_000)
    await startChapter(page, 3)
    await rotateCameraCardinal(page)
    await moveAxis(page, 'z', -0.2, 'line up divider edge')
    await holdKey(page, 'd', 120)
    const current = await readState(page)
    expect(current.player?.position.x ?? 99).toBeLessThan(3.6)
    expect(current.objectives.facts).not.toContain('receiver-filled')
  })

  test('F — jump and dash inputs do not cross the closed Player wall', async ({ page }) => {
    test.setTimeout(150_000)
    await startChapter(page, 3)
    await rotateCameraCardinal(page)
    await page.keyboard.down('d')
    for (let attempt = 0; attempt < 4; attempt += 1) {
      await page.keyboard.down('Space')
      await page.keyboard.down('Shift')
      await advanceTicks(page, 10)
      await page.keyboard.up('Shift')
      await page.keyboard.up('Space')
    }
    await page.keyboard.up('d')
    expect((await readState(page)).player?.position.x ?? 99).toBeLessThan(3.6)
  })

  test('G — closed shutter blocks a Core from entering the transfer lane', async ({ page }) => {
    test.setTimeout(150_000)
    await startChapter(page, 3)
    await recordPlayerCore(page)
    await moveAxis(page, 'z', -2.3, 'enter the Player route')
    await moveAxis(page, 'x', -0.8, 'reach shutter throw point')
    await holdKey(page, 'd', 1)
    await pressKey(page, 'k')
    await advanceTicks(page, 40)
    const current = await readState(page)
    expect(current.barriers?.['transfer-shutter']?.open).toBe(false)
  })

  test('H — open shutter allows the Echo throw to use the same Core', async ({ page }) => {
    test.setTimeout(180_000)
    await startChapter(page, 3)
    await pressKey(page, 'r')
    await holdKey(page, 'd', 54)
    await pressKey(page, 'e')
    await expect.poll(async () => (await readState(page)).cores['memory-core']?.carriedBy).toBe('player')
    await rotateCameraCardinal(page)
    await moveAxis(page, 'z', 1.6, 'enter transfer lane')
    await moveAxis(page, 'x', -0.8, 'reach west throw point')
    await holdKey(page, 'd', 1)
    await pressKey(page, 'k')
    await moveAxis(page, 'x', -1.5, 'line up the Ch3 descent stairs')
    await moveAxis(page, 'z', -2.3, 'line up the Player route')
    await moveAxis(page, 'x', 4.4, 'cross Player route')
    await pressKey(page, 'r')
    await waitForState(page, (current) => current.barriers?.['transfer-shutter']?.open === true, 240, 'shutter did not open for the live Player')
    const replaying = await waitForState(page, (current) => current.echo.tick >= 62, 120, 'Echo did not reach the recorded pickup')
    expect(replaying.cores['memory-core']?.carriedBy).toBe('echo')
    await waitForState(page, (current) => current.echo.mode === 'holding', 420, 'Echo did not complete the physical throw')
    const landed = await readState(page)
    expect(Object.keys(landed.cores)).toEqual(['memory-core'])
    expect(landed.cores['memory-core']?.carriedBy).toBeUndefined()
    expect(landed.cores['memory-core']?.position.x ?? 0).toBeGreaterThan(4)
    expect(landed.objectives.facts).not.toContain('receiver-filled')
  })

  test('I — Player interference leaves Echo unable to duplicate the Core', async ({ page }) => {
    test.setTimeout(180_000)
    await startChapter(page, 3)
    await rotateCameraCardinal(page)
    await pressKey(page, 'r')
    await holdKey(page, 'd', 54)
    await pressKey(page, 'e')
    await holdKey(page, 'a', 18)
    await pressKey(page, 'r')
    await advanceTicks(page, 120)
    const current = await readState(page)
    expect(Object.keys(current.cores)).toEqual(['memory-core'])
    expect(current.cores['memory-core']?.receiver).toBe(false)
  })

  test('J — Echo pickup keeps one canonical Core record', async ({ page }) => {
    test.setTimeout(180_000)
    await startChapter(page, 3)
    await recordPlayerCore(page)
    await pressKey(page, 'r')
    await waitForState(page, (current) => current.echo.tick >= 59, 180, 'Echo did not reach recorded pickup')
    const current = await readState(page)
    expect(Object.keys(current.cores)).toEqual(['memory-core'])
    expect(current.cores['memory-core']?.receiver).toBe(false)
  })

  test('K — a new real recording replaces the previous Echo tape', async ({ page }) => {
    test.setTimeout(180_000)
    await startChapter(page, 3)
    await rotateCameraCardinal(page)
    await pressKey(page, 'r')
    await holdKey(page, 'd', 18)
    await pressKey(page, 'r')
    await expect.poll(async () => (await readState(page)).echoesCreated).toBe(1)
    await pressKey(page, 'r')
    await holdKey(page, 'a', 18)
    await pressKey(page, 'r')
    await expect.poll(async () => (await readState(page)).echoesCreated).toBe(2)
  })

  test('L — EAST to WEST remains blocked by the one-way crossing', async ({ page }) => {
    test.setTimeout(180_000)
    await startChapter(page, 3)
    await rotateCameraCardinal(page)
    await moveAxis(page, 'z', -2.3, 'line up the authored crossing')
    await moveAxis(page, 'x', 4.4, 'cross WEST to EAST')
    const east = await readState(page)
    expect(east.player?.position.x ?? 0).toBeGreaterThan(4)
    await holdKey(page, 'a', 120)
    const blocked = await readState(page)
    expect(blocked.player?.position.x ?? 0, 'the live Player cannot cross EAST to WEST').toBeGreaterThan(3.5)
  })
})
