import { expect, test } from '@playwright/test'
import { advanceTicks, holdKey, moveAxis, pressKey, readState, rotateCameraCardinal, startChapter, waitForState } from './runtime-helpers'

test.describe('Echo Depths keyboard runtime', () => {
  test('Chapter 1 completes with a recorded lever and pressure-plate path', async ({ page }) => {
    test.setTimeout(180_000)
    await startChapter(page, 1)
    await rotateCameraCardinal(page)

    // The Player records only physical keyboard movement and the real lever
    // interaction; Echo must replay the same path onto the pressure plate.
    await pressKey(page, 'r')
    await moveAxis(page, 'z', 0.4, 'reach Chapter 1 lever')
    await moveAxis(page, 'x', -3.9, 'align with Chapter 1 lever')
    await pressKey(page, 'e')
    await moveAxis(page, 'z', 3.2, 'walk to the first plate')
    await moveAxis(page, 'x', -0.9, 'stand on the first plate')
    await pressKey(page, 'r')

    await waitForState(page, (current) => current.pressurePlates?.['echo-plate']?.active === true, 600, 'Echo did not occupy the first plate')
    await moveAxis(page, 'z', 0.4, 'approach the Chapter 1 stairs')
    await moveAxis(page, 'x', 8.1, 'cross the opened stair door', 1_200)
    await moveAxis(page, 'z', -1.2, 'line up the Chapter 1 exit')
    await holdKey(page, 'e', 600)
    const complete = await waitForState(page, (current) => current.mode === 'chapter-complete', 60, 'Chapter 1 did not complete')
    expect(complete.objectives.complete).toBe(true)
    expect(complete.objectives.facts).toContain('tutorial-lever')
    expect(complete.objectives.facts).toContain('echo-plate')
  })

  test('Chapter 2 completes with keyboard Echo lever, elevator ride, and cargo plate', async ({ page }) => {
    test.setTimeout(240_000)
    await startChapter(page, 2)
    await rotateCameraCardinal(page)

    // Record the Echo's real lever hold. The Player then rides the physical
    // elevator, moves the real cargo crate, and uses the actual exit.
    await pressKey(page, 'r')
    await moveAxis(page, 'z', -1.2, 'reach the counterweight lever')
    await moveAxis(page, 'x', -3.6, 'align with the counterweight lever')
    await holdKey(page, 'e', 600)
    await pressKey(page, 'r')
    await waitForState(page, (current) => current.levers?.['lift-lever']?.actor === 'echo', 600, 'Echo did not hold the counterweight lever')
    await moveAxis(page, 'x', -1.0, 'approach the counterweight elevator')
    await moveAxis(page, 'z', -0.7, 'approach the counterweight elevator from the west')
    await page.keyboard.down('d')
    await page.keyboard.down('Space')
    await advanceTicks(page, 18)
    await page.keyboard.up('Space')
    await page.keyboard.up('d')
    await advanceTicks(page, 2)
    await waitForState(page, (current) => (current.elevators?.['counter-elevator']?.y ?? 0) > 3, 900, 'counterweight elevator did not rise')

    await moveAxis(page, 'x', 5.7, 'reach the upper cargo')
    await moveAxis(page, 'z', 1.6, 'align with the upper cargo')
    await pressKey(page, 'e')
    await expect.poll(async () => (await readState(page)).crates?.['cargo-crate']?.carriedBy, { timeout: 15_000 }).toBe('player')
    await moveAxis(page, 'x', 0.2, 'carry cargo to the elevator')
    await moveAxis(page, 'z', -0.7, 'board the elevator with cargo')
    await waitForState(page, (current) => (current.elevators?.['counter-elevator']?.y ?? 1) < 1, 900, 'counterweight elevator did not return to the lower floor')
    await moveAxis(page, 'x', 1.3, 'carry cargo toward the weight plate')
    await page.keyboard.down('s')
    await page.keyboard.down('Space')
    await advanceTicks(page, 18)
    await page.keyboard.up('Space')
    await page.keyboard.up('s')
    await advanceTicks(page, 2)
    await page.keyboard.down('d')
    await page.keyboard.down('Space')
    await advanceTicks(page, 12)
    await page.keyboard.up('Space')
    await page.keyboard.up('d')
    await advanceTicks(page, 2)
    await moveAxis(page, 'z', 3.7, 'line up the weight plate')
    await pressKey(page, 'e')
    await waitForState(page, (current) => current.objectives.facts.includes('cargo-plate'), 300, 'cargo did not settle on the weight plate')
    await moveAxis(page, 'x', 2.7, 'walk to the lower counterweight exit')
    await moveAxis(page, 'z', 3.7, 'line up the lower counterweight exit')
    await pressKey(page, 'e')
    const complete = await waitForState(page, (current) => current.mode === 'chapter-complete', 60, 'Chapter 2 did not complete')
    expect(complete.objectives.complete).toBe(true)
    expect(complete.objectives.facts).toContain('lift-lever-echo')
    expect(complete.objectives.facts).toContain('elevator-ridden')
    expect(complete.objectives.facts).toContain('cargo-plate')
  })
})
